version: 2

jobs:
  cms:
    docker:
      - image: circleci/python:3.9.6
    working_directory: ~/CMS
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}
            - pip-packages-v1-
      - save_cache:
          paths:
            - ~/.local/
          key: pip-package-v1-{{ .Branch }}
      - run: |
          python3 -m venv env
          . ./env/bin/activate
          cd ~/CMS/logknot
          pip3 install -r requirements.txt
      - run: |
          cd ~/CMS
          . ./env/bin/activate
          ./unit_test.sh

workflows:
    version: 2
    test:
      jobs:
        - cms
