# Generated by Django 3.2.5 on 2021-07-27 09:20

from django.db import migrations, models
import django.db.models.deletion
import home.streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_permission_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))])), ('full_richtext', home.streams.blocks.RichtextBlock()), ('simple_richtext', home.streams.blocks.SimpleRichtextBlock())], blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='keyword',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.buildingimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_url',
            field=models.URLField(default='', max_length=255),
        ),
    ]
