# Generated by Django 3.2.5 on 2021-08-06 03:46
from django.db import migrations
from django.conf import settings


def create_contentpage(apps, schema_editor):
    from home.models import HomePage
    from content.models import ContentPage

    # Get models
    ContentType = apps.get_model('contenttypes.ContentType')

    contentpage_content_type, __ = ContentType.objects.get_or_create(
        model='contentpage', app_label='content')

    home_page = HomePage.objects.get(id=3)
    if home_page:
        home_page.add_child(
            instance=ContentPage(
                title="Content buildings page",
            )
        )


def remove_contentpage(apps, schema_editor):
    from content.models import ContentPage
    ContentPage.objects.get().delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
        ('home', '0008_auto_20210806_0114'),
    ]

    operations = [
        migrations.RunPython(
            create_contentpage, remove_contentpage
        ),
    ]
